### ISSUE TITLE
The primary category isn't assigned for variants. 

### ISSUE THREAD

**Issue by brianshenPixleeTurnto** [turnto/salesforce-commerce-cloud#60]
https://github.com/turnto/salesforce-commerce-cloud/blob/d3ba5c98fff416be597d4d5e75b3370cae875a53/cartridges/int_turnto_core_v5/cartridge/scripts/jobsteps/ExportCatalog.js#L177

We need category to be assigned for variants to used TT subdimensions.

**Comment by brianshenPixleeTurnto** [comment]
better to use https://salesforcecommercecloud.github.io/b2c-dev-doc/docs/current/scriptapi/html/api/class_dw_catalog_Product.html#dw_catalog_Product_getAllCategories_DetailAnchor

**Comment by ptrollinspt** [comment]
Release 1.3.0 has an update to use the parent's category for the variant.
